substitutions:
  board       : "m5stack-atom"
  
  # I2C
  pin_scl: "GPIO22"
  pin_sda: "GPIO21"

  # 
  pin_mosi: "GPIO26"
  pin_miso: "GPIO36"
  pin_sck: "GPIO18"
  pin_cs: "GPIO19"

  pin_dac: "GPIO25"
  pin_led: "GPIO27"

  # Serial
  pin_tx0: "GPIO1"
  pin_rx0: "GPIO3"

  # XH Connector
  con_3: "GPIO32"
  con_4: "GPIO33"

  
esphome:
  name_add_mac_suffix: false

esp32:
  board: ${board}
  framework:
    type: arduino

# Modules
api:
captive_portal:
improv_serial:
# esp32_improv:
#   authorizer: none
web_server:
logger:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: $pin_led
    num_leds: 1
    rgb_order: GRB
    id: ${name}_led
    name: ${name} Status LED
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
      - pulse: