packages:
  device        : !include devices/m5stamp.yaml
  app           : !include apps/cabinet_fan.yaml
  wifi          : !include inc/wifi.yaml
  info          : !include inc/info.yaml
#  ble           : !include inc/ble_proxy.yaml

substitutions:
#  mac           : "bb20"
#  mac           : "a2ac"
  mac           : "9548"

# wifi:
#   use_address:  192.168.0.240
