substitutions:
  xs: "10"
  s: "15"
  m: "20"
  l: "30"

font:
  - file: "../pac/esphome/fonts/DejaVuSans.ttf"
    id: sans_s
    size: $s
#    glyphs: [0,1,2,3,4,5,6,7,8,9,".","-"," ",":","K","W","H","%"]

  - file: "../pac/esphome/fonts/DejaVuSans.ttf"
    id: sans_l
    size: $l
#    glyphs: [0,1,2,3,4,5,6,7,8,9,".","-"," ","%"]

  - file: '../pac/esphome/fonts/material/fonts/materialdesignicons-webfont.ttf'
    id: mdi_s
    size: $s
    glyphs:
      - "\U000F060A" # mdi-signal-variant
      - "\U000F0954" # mdi-clock
      