substitutions:
  name        : "m5-stack"
  mac         : "0000"
  address     : "${name}_${mac}.local"
  
  ## DISPLAY
  cs_pin      : "14"
  dc_pin      : "27"
  led_pin     : "32"
  reset_pin   : "33"
  
esphome:
  name: ${name}_${mac}
  name_add_mac_suffix: false

esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino

# Modules
logger:
api:
captive_portal:
improv_serial:
web_server:
# esp32_improv:
#   authorizer: none

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

# Download Roboto font from https://fonts.google.com/specimen/Roboto
font:
  - file: "../pac/esphome/fonts/roboto/Roboto-Medium.ttf"
    id: font_roboto_medium22
    size: 22
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/³µ'

# display:
#   - platform: ili9341
#     id: m5stack_display
#     model: M5Stack
#     cs_pin: $cs_pin
#     dc_pin: $dc_pin
#     led_pin: $led_pin
#     reset_pin: $reset_pin
#     rotation: 0
#     lambda: |-
#       // colour aliases
#       auto red = Color(0, 255, 255);
#       auto green = Color(255,0,255);
#       auto blue = Color(255, 255, 0);
#       auto white = Color(0, 0, 0);
#       auto black = Color(255,255,255);
#       
#       it.fill(black);
#       
#       it.print(0, 0, id(font_roboto_medium22), blue, TextAlign::TOP_LEFT, "Hello World!");
#       it.printf(0,23, id(font_roboto_medium22), white, "%.0f %%", (id(wifi_sig).state)+101);



# button A (GPIO39), button B (GPIO38) and button C (GPIO37)
# Button to toggle the display backlight
binary_sensor:
  - platform: gpio
    id: but_a
    pin:
      number: 39
      inverted: true
    
  - platform: gpio
    id: but_b
    pin:
      number: 38
      inverted: true
    on_click:
      then:
        - switch.toggle: backlight

  - platform: gpio
    id: but_c
    pin:
      number: 37
      inverted: true
      
switch:
  - platform: gpio
    pin: 32
    name: "Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

# output:
#   - platform: ledc
#     pin: 32
#     id: backlight
#     name: "Backlight"
#     brightness: 50%
    
    
    
    
    
    
