# https://github.com/esphome/issues/issues/2931
substitutions:
  pin_led: "GPIO2"

  # I2C
  pin_sda: "GPIO5"
  pin_scl: "GPIO6"

  pin_a0: "GPIO4"
  pin_a1: "GPIO3"
  pin_a2: "GPIO1"
  pin_a3: "GPIO0"

  # Serial
  pin_tx: "GPIO21"
  pin_rx: "GPIO20"

  # SPI
  pin_sck: "GPIO10"
  pin_miso: "GPIO8"
  pin_mosi: "GPIO7"

esphome:
  platformio_options:
    board_build.flash_mode: dio
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.1
    platform:
      - https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream

esp32:
  board: "esp32-c3-devkitm-1"
#  board: adafruit_qtpy_esp32c3
  variant: ESP32C3
  framework:
    type: arduino

## MODULES
##########
api:
captive_portal:
# improv_serial:
logger:
# esp32_improv:
#   authorizer: none
web_server:

# i2c:
#   - id: stemma
#     sda: $pin_sda
#     scl: $pin_scl
#     scan: true

light:
  - platform: neopixelbus
    id: led_neo
    name: LED
    type: GRB
    variant: WS2812x
    method: ESP32_RMT_1
    num_leds: 1
    pin: $pin_led
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
      - pulse:
