# HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
# RAM:   [=         ]  12.8% (used 41868 bytes from 327680 bytes)
# Flash: [======    ]  56.1% (used 1029702 bytes from 1835008 bytes)
# Wrote 0x10b6b0 bytes to file /data/m5stamp-dev_bb20/.pioenvs/m5stamp-dev_bb20/firmware-factory.bin, ready to flash to offset 0x0

packages:
  device        : !include devices/m5stamp.yaml
  wifi          : !include inc/wifi.yaml
  info          : !include inc/info.yaml
  # ble           : !include inc/ble_proxy.yaml

substitutions:
  app: "m5stamp-dev"
  mac: "bb20"

esphome:
  name: ${app}_${mac}
  on_boot:
    light.turn_on:
      id: ${name}_led
      effect: pulse
      brightness: 10%
      red: 0%
      green: 100%
      blue: 0%

# wifi:
#   use_address:  192.168.0.237

esp32_ble_tracker:
external_components:
  - source: github://myhomeiot/esphome-components

ble_gateway:
  on_ble_advertise:
    then:
      homeassistant.event:
        event: esphome.on_ble_advertise
        data: 
            packet: !lambda return packet;
