packages:
  wifi: !include inc/wifi_uk.yaml

wifi:
  use_address:  192.168.1.30

substitutions:
  mac: "54cc"
  devicename: nspanel

esphome:
  name: ${devicename}-${mac}

esp32:
  board: esp32dev

logger:
captive_portal:
    