esphome:
  name: ${name}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Modules
logger:
api:
improv_serial:
# esp32_improv:
#   authorizer: none
captive_portal:
web_server:
